### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException

### ISSUE THREAD

**Issue by raphi** [sergdort/SHUImagePickerController#2]
Hi,

I got a repeated weird crash on SHUCropImageController.m line 149:
```Fatal Exception: NSInternalInconsistencyException
Constant is not finite! That's illegal. constant:nan```

It seems that it's working fine for recent photos, but when I select older photos, I got this crash.

Any idea?

Thanks

**Comment by sergdort** [comment]
@raphi 
Hi, are you using it from cocoapods?

**Comment by sergdort** [comment]
@raphi constant:nan looks like there is some division by 0 in the my math

**Comment by sergdort** [comment]
@raphi try to put breakpoint in method
I guess only here u could get "nan"
- (CGSize) _contentSizeForImage:(UIImage *)image{

}

**Comment by raphi** [comment]
@sergdort yes I used cocoapods. Ok will try that.

**Comment by raphi** [comment]
@sergdort actually it works fine on my env. The error comes from one of my remote tester by crash reporting, so I cannot really debug it.

Here is what I can see:
<img width="961" alt="screen shot 2015-08-14 at 12 28 18 pm" src="https://cloud.githubusercontent.com/assets/783964/9272167/08d214d0-4280-11e5-8187-3bd7a157bf28.png">

**Comment by sergdort** [comment]
I guess you you can to reproduce this by trying to pick image from camera.
Could you please try. And if it appears then please use the following set up of pod file:

pod 'SHUImagePickerController', :git => 'https://github.com/sergdort/SHUImagePickerController.git', :branch => 'master'

PS. This way you will have the latest changes. Sorry have not ship the next version yet

**Comment by raphi** [comment]
I'm only using the photo library as source type (UIImagePickerControllerSourceTypeSavedPhotosAlbum). Ok I will update it and will see if it fix the bug for the remote tester. Will keep up to date, thank :)

**Comment by raphi** [comment]
@sergdort with the master version, the bug goes away. Thanks for you fast support :) :+1:
