### ISSUE TITLE
Cropsize error on iPhone 6

### ISSUE THREAD

**Issue by raphi** [sergdort/SHUImagePickerController#3]
Hi,

it seems there is a bug on iPhones where the screen width is > 320:

![img_0185](https://cloud.githubusercontent.com/assets/783964/10816511/810daace-7e33-11e5-8fb9-5cef1b37d0c9.PNG)

I changed the crop size to be related to the current screen size (example: 320x100 on iPhone 5 to 375x117 on iPhone 6). Even if I set the width to 600, nothing change, it does not take the full width and stay like the screenshot above. And it seems to be off the screen on the left.

Any idea?

Thank you

**Comment by sergdort** [comment]
Hi, @raphi I guess the problem with hardcoded sizes of the screen, going to fix this on the weekend

**Comment by raphi** [comment]
@sergdort awesome let me know

**Comment by sergdort** [comment]
Hi @raphi  I fixed bugs on iPhones, there is bug for iPad though, but if you don't need iPad support you can use it now

**Comment by raphi** [comment]
@sergdort thanks for your fast response! I will test it this week. I'm definitely gonna use it on iPad but not right now.

**Comment by raphi** [comment]
@sergdort it works great thanks! Let me know when you do it for iPad.

**Comment by sergdort** [comment]
Hey, @raphi , I've fixed the bug on iPad. Please take a look

**Comment by raphi** [comment]
@sergdort is it supposed to be open in a popup view?

**Comment by sergdort** [comment]
@raphi yes it always was in popup for iPads. Do you think, I't would be great to have API to open it in modal only ?

**Comment by raphi** [comment]
Hey @sergdort I'm not sure what I will use yet on iPad. This is currently fine for me. But yeah, having the option would be nice and make this pod more generic.
